### ISSUE TITLE
Support OneLogin as backend

### ISSUE THREAD

**Issue by dan-tabarca** [python-social-auth/social-core#656]
As Python-social-auth library supports many backends, would be great if it can support also authentication with OneLogin.

**Comment by ezrajrice** [comment]
Not sure if you have already figured this out, but you can use the OpenIdConnectAuth backend for OneLogin. The important settings to configure in the OAUTH_CONFIG section are

```yaml
  SOCIAL_AUTH_ONELOGIN_OIDC_KEY: <sso_key>
  SOCIAL_AUTH_ONELOGIN_OIDC_SECRET: <sso_secret>
  SOCIAL_AUTH_ONELOGIN_OIDC_ENDPOINT: https://example.onelogin.com/oidc/2
  SOCIAL_AUTH_ONELOGIN_OIDC_TOKEN_ENDPOINT_AUTH_METHOD: POST
```

The TOKEN_ENDPOINT_AUTH_METHOD defaults to GET so if the SSO is configured to only accept POST requests, then it needs to be set here. Hope this helps.

NOTE: I've been working in a project that sub-classed OpenIdConnectAuth so that we could redefine the OIDC_ENDPOINT property for simplicity so just double check the above key value pairs have the correct keys.
